server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/infoguru
    username: infoguru
    password: Earphone9-Unfixed-Docile-Catchable-Heat-Stash
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet
quizgpt:
  app:
    jwtSecret: "grJ5BrxzFE5J3vaQTEFosrE7twmUMXD4HgQCJBzRTpRJ59PLUUhJcx5RfcNynKyDiLLCg8o4bgQwf94Sagxa5kL58pH7HFTdkA3AMynx397WRVrt9zZLr2G46aPVzVZS"
    jwtExpirationMs: 86400000
